### ISSUE TITLE
[feature] Support for multiple s3 endpoint addresses?

### ISSUE THREAD

**Issue by PC-Admin** [clyso/chorus#36]
We're examining ways to sync a tremendous amount of data between 2x clusters (think >10PiB). One way we were hoping to speed the process up was to have multiple physical RGWs on each cluster sitting dormant, that would then be used by Chorus.

I am noticing that Chorus seems to support in it's "address" field either a single IP or URL. Is their anyway to get Chorus to use an array of IPs instead? I'd like to basically read directly out of a large array of RGWs and write into another array of RGWs sitting in the following cluster.

If there's not a way to do something equivalent with Chorus it could be a good feature to have. (our loadbalancers tend to really bottleneck our RGWs a lot so we were hoping to just go around them!)

**Comment by arttor** [comment]
I am not sure that we can support multiple s3 addresses because it is not supported by rclone and s3 client libs used in chorus. 

You can try to load balance migrations by buckets but it will require some manual steps and will only make sense if you have rather small amount of buckets:

1. list your buckets and split it in `N` equal "groups" (by size or by obj count), where `N` is number of RGWs
2. spawn `N` chorus instances. assign each chorus to each GRW
3. assign one bucket "group" to one chorus instance, by manually creating bucket replication policy for each bucket from the "group"

**Comment by PC-Admin** [comment]
Hi @arttor, thank you for the quick response.

I was thinking some DNS hackery could be the solution here.

Let's say I have 20x "dormant" RGWs sitting in the main cluster, and 20x in the following cluster. I could create a fake endpoint name and hard-code the IP address of just 1x RGW in each hosts `/etc/hosts` file in the following cluster.

That way, the following RGWs would all think they're talking to the same endpoint (effectively they would be) and we'd get 20x transfers happening at once!

I guess that would work?

**Comment by PC-Admin** [comment]
Closing now as this features unlikely to to be implemented.
