### ISSUE TITLE
ResourceExhausted with `chorctl check`

### ISSUE THREAD

**Issue by mtse-btg** [clyso/chorus#43]
Hello Clyso team,

## Scenario
* We recently completed a replication, but encountered the following error when attempted to run `chorctl check`
    ```
    $ chorctl check XXX YYY --check-bucket=BBB --user=UUU
    Checking files in bucket BBB ...
    🪣 BUCKET   | Match     | MissSrc     | MissDst     | Differ     | Error
    FATA[0031] unable to check bucket                        error="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (24073513 vs. 4194304)"
    ```
## Replication info
* Size of the replicated bucket: 449.9 GiB
* Number of objects: 131094
## Questions
* Would the issue be because gRPC is currently only accepting messages no larger than 4MB?
* Please could your team assist in resolving the above error?

Thanks.

**Comment by arttor** [comment]
Hi @mtse-btg. `chorctl check` is just a wrapper around [rclone check](https://rclone.org/commands/rclone_check/) command which is executed on chorus worker. 

We will have to rewrite it or remove it because `rclone check` consumes **a lot** of RAM and takes a lot of time for big bucket and can fail chorus worker instance. So it was a bad idea to add this command to chorctl as it is.

Please try to use [rclone check](https://rclone.org/commands/rclone_check/) directly instead of chorctl check to avoid timeout error.
